import { useState } from 'react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Button } from '@/components/ui/button';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Loader2, Hash, AlertCircle, Check } from 'lucide-react';
import { useGetCallerUserProfile, useSaveCallerUserProfile } from '../../hooks/useQueries';
import { toast } from 'sonner';

interface IdClaimDialogProps {
  open: boolean;
  onComplete: () => void;
}

export default function IdClaimDialog({ open, onComplete }: IdClaimDialogProps) {
  const { data: userProfile } = useGetCallerUserProfile();
  const saveProfile = useSaveCallerUserProfile();
  const [customId, setCustomId] = useState('');
  const [error, setError] = useState('');
  const [showCustomInput, setShowCustomInput] = useState(false);

  const autoGeneratedId = userProfile?.userId || '';

  const validateCustomId = (value: string): boolean => {
    if (value.length !== 6) {
      setError('ID must be exactly 6 characters');
      return false;
    }

    const isValidAlphanumeric = /^[A-Z0-9]{6}$/.test(value.toUpperCase());
    if (!isValidAlphanumeric) {
      setError('ID must only contain letters and numbers');
      return false;
    }

    setError('');
    return true;
  };

  const handleCustomIdChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value.toUpperCase().slice(0, 6);
    setCustomId(value);
    
    if (value.length > 0) {
      validateCustomId(value);
    } else {
      setError('');
    }
  };

  const handleAcceptAutoGenerated = async () => {
    if (!userProfile) {
      toast.error('Profile not loaded');
      return;
    }

    try {
      await saveProfile.mutateAsync(userProfile);
      toast.success(`ID ${autoGeneratedId} claimed successfully!`);
      onComplete();
    } catch (error: any) {
      console.error('Failed to claim ID:', error);
      toast.error(error.message || 'Failed to claim ID');
    }
  };

  const handleCreateCustomId = async () => {
    if (!validateCustomId(customId)) {
      return;
    }

    if (!userProfile) {
      toast.error('Profile not loaded');
      return;
    }

    try {
      const updatedProfile = {
        ...userProfile,
        userId: customId.toUpperCase(),
      };
      await saveProfile.mutateAsync(updatedProfile);
      toast.success(`Custom ID ${customId.toUpperCase()} created successfully!`);
      onComplete();
    } catch (error: any) {
      console.error('Failed to create custom ID:', error);
      const errorMessage = error.message || 'Failed to create custom ID';
      
      if (errorMessage.includes('already exists') || errorMessage.includes('already taken')) {
        setError('This ID is already taken. Please try a different one.');
        toast.error('ID already taken');
      } else {
        setError(errorMessage);
        toast.error('Failed to create custom ID');
      }
    }
  };

  return (
    <Dialog open={open} onOpenChange={() => {}}>
      <DialogContent 
        className="sm:max-w-md" 
        onPointerDownOutside={(e) => e.preventDefault()} 
        onEscapeKeyDown={(e) => e.preventDefault()}
      >
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Hash className="h-5 w-5 text-primary" />
            Claim Your ID
          </DialogTitle>
          <DialogDescription>
            Your unique 6-character ID has been generated. Accept it or create your own custom ID.
          </DialogDescription>
        </DialogHeader>
        
        {!showCustomInput ? (
          <div className="space-y-6">
            <div className="rounded-lg border border-primary/20 bg-primary/5 p-6 text-center">
              <p className="text-sm text-muted-foreground mb-2">Your Auto-Generated ID</p>
              <p className="text-4xl font-bold tracking-wider text-primary mb-4">
                {autoGeneratedId}
              </p>
              <Button
                onClick={handleAcceptAutoGenerated}
                disabled={saveProfile.isPending}
                className="w-full"
                size="lg"
              >
                {saveProfile.isPending ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Claiming...
                  </>
                ) : (
                  <>
                    <Check className="mr-2 h-4 w-4" />
                    Accept This ID
                  </>
                )}
              </Button>
            </div>

            <div className="relative">
              <div className="absolute inset-0 flex items-center">
                <span className="w-full border-t" />
              </div>
              <div className="relative flex justify-center text-xs uppercase">
                <span className="bg-background px-2 text-muted-foreground">Or</span>
              </div>
            </div>

            <Button
              variant="outline"
              onClick={() => setShowCustomInput(true)}
              className="w-full"
            >
              Create Custom ID (Free)
            </Button>
          </div>
        ) : (
          <div className="space-y-4">
            {error && (
              <Alert variant="destructive">
                <AlertCircle className="h-4 w-4" />
                <AlertDescription>{error}</AlertDescription>
              </Alert>
            )}
            
            <div className="space-y-2">
              <Label htmlFor="customId">
                Custom ID (6 characters, letters and numbers only)
              </Label>
              <Input
                id="customId"
                type="text"
                placeholder="ABC123"
                value={customId}
                onChange={handleCustomIdChange}
                disabled={saveProfile.isPending}
                className={`text-center text-2xl font-bold tracking-wider uppercase ${error ? 'border-destructive' : ''}`}
                maxLength={6}
                autoFocus
              />
              <p className="text-xs text-muted-foreground text-center">
                Enter exactly 6 characters (e.g., ABC123, X7Y9Z4)
              </p>
            </div>

            <div className="flex gap-2">
              <Button
                variant="outline"
                onClick={() => {
                  setShowCustomInput(false);
                  setCustomId('');
                  setError('');
                }}
                disabled={saveProfile.isPending}
                className="flex-1"
              >
                Back
              </Button>
              <Button
                onClick={handleCreateCustomId}
                disabled={saveProfile.isPending || customId.length !== 6}
                className="flex-1"
              >
                {saveProfile.isPending ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Creating...
                  </>
                ) : (
                  'Create Custom ID'
                )}
              </Button>
            </div>
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
}
