/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'productId' : string, 'quantity' : bigint }
export interface Category { 'name' : string, 'description' : string }
export type CustomUsernameStatus = { 'pendingReview' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface CustomUsernameSubmission {
  'status' : CustomUsernameStatus,
  'paymentMethod' : PaymentMethod,
  'transactionDetails' : string,
  'user' : Principal,
  'requestedUsername' : string,
  'timestamp' : Time,
}
export interface ExtendedQueueSkipSubmission {
  'username' : [] | [string],
  'submission' : QueueSkipSubmission,
}
export type ExternalBlob = Uint8Array;
export type GiftCardType = { 'cryptocurrency' : null } |
  { 'tesco' : null } |
  { 'other' : null } |
  { 'starbucks' : null } |
  { 'amazon' : null };
export interface PaymentConfig {
  'queueSkipPriceGBP' : number,
  'instagramUrl' : string,
  'cryptoWalletAddress' : string,
  'ukGiftCardInstructions' : string,
  'usernameRegenerationPriceGBP' : number,
  'customUsernamePriceGBP' : number,
  'paypalEmail' : string,
}
export type PaymentMethod = { 'crypto' : null } |
  { 'giftCard' : null } |
  { 'paypal' : null };
export interface Product {
  'id' : string,
  'imageUrls' : Array<string>,
  'name' : string,
  'description' : string,
  'productType' : ProductType,
  'image' : ExternalBlob,
  'priceGBP' : number,
  'quantityAvailable' : bigint,
  'gameCategory' : string,
}
export type ProductType = { 'clothes' : null } |
  { 'currency' : null } |
  { 'account' : null };
export type QueueSkipStatus = { 'pendingReview' : null } |
  { 'flaggedFraudulent' : null } |
  { 'approved' : null };
export interface QueueSkipSubmission {
  'status' : QueueSkipStatus,
  'user' : Principal,
  'giftCardCode' : [] | [string],
  'giftCardType' : GiftCardType,
  'timestamp' : Time,
  'transactionId' : string,
}
export type Time = bigint;
export interface UserProfile {
  'username' : [] | [string],
  'name' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAdminUsername' : ActorMethod<[string], undefined>,
  'addToCart' : ActorMethod<[string, bigint], undefined>,
  'approveCustomUsername' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'createCategory' : ActorMethod<[string, Category], undefined>,
  'createProduct' : ActorMethod<[string, Product], undefined>,
  'createUsername' : ActorMethod<[string], undefined>,
  'deleteCategory' : ActorMethod<[string], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'flagQueueSkipFraud' : ActorMethod<[Principal], undefined>,
  'getAllCategories' : ActorMethod<[], Array<Category>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getCategory' : ActorMethod<[string], Category>,
  'getCustomUsernameSubmissions' : ActorMethod<
    [],
    Array<CustomUsernameSubmission>
  >,
  'getInstagramUrl' : ActorMethod<[], string>,
  'getPaymentDetails' : ActorMethod<[], PaymentConfig>,
  'getProduct' : ActorMethod<[string], Product>,
  'getQueueSkipSubmissions' : ActorMethod<[], Array<QueueSkipSubmission>>,
  'getQueueSkipSubmissionsWithUsernames' : ActorMethod<
    [],
    Array<ExtendedQueueSkipSubmission>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUsername' : ActorMethod<[Principal], [] | [string]>,
  'hasQueueBypass' : ActorMethod<[], boolean>,
  'hasUsername' : ActorMethod<[], boolean>,
  'isAdminUsername' : ActorMethod<[string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rejectCustomUsername' : ActorMethod<[Principal], undefined>,
  'removeAdminUsername' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitCustomUsername' : ActorMethod<
    [string, PaymentMethod, string],
    undefined
  >,
  'submitQueueSkipPayment' : ActorMethod<
    [string, GiftCardType, [] | [string]],
    undefined
  >,
  'updateCartItemQuantity' : ActorMethod<[string, bigint], undefined>,
  'updateCategory' : ActorMethod<[string, Category], undefined>,
  'updatePaymentDetails' : ActorMethod<[PaymentConfig], undefined>,
  'updateProduct' : ActorMethod<[string, Product], undefined>,
  'validateGeneratedUsername' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];