/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const ProductType = IDL.Variant({
  'clothes' : IDL.Null,
  'currency' : IDL.Null,
  'account' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Product = IDL.Record({
  'id' : IDL.Text,
  'imageUrls' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'productType' : ProductType,
  'image' : ExternalBlob,
  'priceGBP' : IDL.Float64,
  'quantityAvailable' : IDL.Nat,
  'gameCategory' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Opt(IDL.Text),
  'userId' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const CartItem = IDL.Record({
  'productId' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const CustomUsernameStatus = IDL.Variant({
  'pendingReview' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'crypto' : IDL.Null,
  'giftCard' : IDL.Null,
  'paypal' : IDL.Null,
});
export const Time = IDL.Int;
export const CustomUsernameSubmission = IDL.Record({
  'status' : CustomUsernameStatus,
  'paymentMethod' : PaymentMethod,
  'transactionDetails' : IDL.Text,
  'user' : IDL.Principal,
  'requestedUsername' : IDL.Text,
  'timestamp' : Time,
});
export const PaymentConfig = IDL.Record({
  'queueSkipPriceGBP' : IDL.Float64,
  'instagramUrl' : IDL.Text,
  'cryptoWalletAddress' : IDL.Text,
  'ukGiftCardInstructions' : IDL.Text,
  'usernameRegenerationPriceGBP' : IDL.Float64,
  'customUsernamePriceGBP' : IDL.Float64,
  'paypalEmail' : IDL.Text,
});
export const QueueSkipStatus = IDL.Variant({
  'pendingReview' : IDL.Null,
  'flaggedFraudulent' : IDL.Null,
  'approved' : IDL.Null,
});
export const GiftCardType = IDL.Variant({
  'cryptocurrency' : IDL.Null,
  'tesco' : IDL.Null,
  'other' : IDL.Null,
  'starbucks' : IDL.Null,
  'amazon' : IDL.Null,
});
export const QueueSkipSubmission = IDL.Record({
  'status' : QueueSkipStatus,
  'user' : IDL.Principal,
  'giftCardCode' : IDL.Opt(IDL.Text),
  'giftCardType' : GiftCardType,
  'timestamp' : Time,
  'transactionId' : IDL.Text,
});
export const ExtendedQueueSkipSubmission = IDL.Record({
  'username' : IDL.Opt(IDL.Text),
  'submission' : QueueSkipSubmission,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAdminUsername' : IDL.Func([IDL.Text], [], []),
  'addToCart' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'approveCustomUsername' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'createCategory' : IDL.Func([IDL.Text, Category], [], []),
  'createProduct' : IDL.Func([IDL.Text, Product], [], []),
  'createUsername' : IDL.Func([IDL.Text], [], []),
  'deleteCategory' : IDL.Func([IDL.Text], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'flagQueueSkipFraud' : IDL.Func([IDL.Principal], [], []),
  'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getCategory' : IDL.Func([IDL.Text], [Category], ['query']),
  'getCustomUsernameSubmissions' : IDL.Func(
      [],
      [IDL.Vec(CustomUsernameSubmission)],
      ['query'],
    ),
  'getInstagramUrl' : IDL.Func([], [IDL.Text], ['query']),
  'getPaymentDetails' : IDL.Func([], [PaymentConfig], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
  'getQueueSkipSubmissions' : IDL.Func(
      [],
      [IDL.Vec(QueueSkipSubmission)],
      ['query'],
    ),
  'getQueueSkipSubmissionsWithUsernames' : IDL.Func(
      [],
      [IDL.Vec(ExtendedQueueSkipSubmission)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUsername' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Text)], ['query']),
  'hasQueueBypass' : IDL.Func([], [IDL.Bool], ['query']),
  'hasUsername' : IDL.Func([], [IDL.Bool], ['query']),
  'isAdminUsername' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rejectCustomUsername' : IDL.Func([IDL.Principal], [], []),
  'removeAdminUsername' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitCustomUsername' : IDL.Func(
      [IDL.Text, PaymentMethod, IDL.Text],
      [],
      [],
    ),
  'submitQueueSkipPayment' : IDL.Func(
      [IDL.Text, GiftCardType, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updateCartItemQuantity' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateCategory' : IDL.Func([IDL.Text, Category], [], []),
  'updatePaymentDetails' : IDL.Func([PaymentConfig], [], []),
  'updateProduct' : IDL.Func([IDL.Text, Product], [], []),
  'validateGeneratedUsername' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Record({ 'name' : IDL.Text, 'description' : IDL.Text });
  const ProductType = IDL.Variant({
    'clothes' : IDL.Null,
    'currency' : IDL.Null,
    'account' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Product = IDL.Record({
    'id' : IDL.Text,
    'imageUrls' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'productType' : ProductType,
    'image' : ExternalBlob,
    'priceGBP' : IDL.Float64,
    'quantityAvailable' : IDL.Nat,
    'gameCategory' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Opt(IDL.Text),
    'userId' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
  });
  const CartItem = IDL.Record({ 'productId' : IDL.Text, 'quantity' : IDL.Nat });
  const CustomUsernameStatus = IDL.Variant({
    'pendingReview' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'crypto' : IDL.Null,
    'giftCard' : IDL.Null,
    'paypal' : IDL.Null,
  });
  const Time = IDL.Int;
  const CustomUsernameSubmission = IDL.Record({
    'status' : CustomUsernameStatus,
    'paymentMethod' : PaymentMethod,
    'transactionDetails' : IDL.Text,
    'user' : IDL.Principal,
    'requestedUsername' : IDL.Text,
    'timestamp' : Time,
  });
  const PaymentConfig = IDL.Record({
    'queueSkipPriceGBP' : IDL.Float64,
    'instagramUrl' : IDL.Text,
    'cryptoWalletAddress' : IDL.Text,
    'ukGiftCardInstructions' : IDL.Text,
    'usernameRegenerationPriceGBP' : IDL.Float64,
    'customUsernamePriceGBP' : IDL.Float64,
    'paypalEmail' : IDL.Text,
  });
  const QueueSkipStatus = IDL.Variant({
    'pendingReview' : IDL.Null,
    'flaggedFraudulent' : IDL.Null,
    'approved' : IDL.Null,
  });
  const GiftCardType = IDL.Variant({
    'cryptocurrency' : IDL.Null,
    'tesco' : IDL.Null,
    'other' : IDL.Null,
    'starbucks' : IDL.Null,
    'amazon' : IDL.Null,
  });
  const QueueSkipSubmission = IDL.Record({
    'status' : QueueSkipStatus,
    'user' : IDL.Principal,
    'giftCardCode' : IDL.Opt(IDL.Text),
    'giftCardType' : GiftCardType,
    'timestamp' : Time,
    'transactionId' : IDL.Text,
  });
  const ExtendedQueueSkipSubmission = IDL.Record({
    'username' : IDL.Opt(IDL.Text),
    'submission' : QueueSkipSubmission,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAdminUsername' : IDL.Func([IDL.Text], [], []),
    'addToCart' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'approveCustomUsername' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'createCategory' : IDL.Func([IDL.Text, Category], [], []),
    'createProduct' : IDL.Func([IDL.Text, Product], [], []),
    'createUsername' : IDL.Func([IDL.Text], [], []),
    'deleteCategory' : IDL.Func([IDL.Text], [], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'flagQueueSkipFraud' : IDL.Func([IDL.Principal], [], []),
    'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getCategory' : IDL.Func([IDL.Text], [Category], ['query']),
    'getCustomUsernameSubmissions' : IDL.Func(
        [],
        [IDL.Vec(CustomUsernameSubmission)],
        ['query'],
      ),
    'getInstagramUrl' : IDL.Func([], [IDL.Text], ['query']),
    'getPaymentDetails' : IDL.Func([], [PaymentConfig], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
    'getQueueSkipSubmissions' : IDL.Func(
        [],
        [IDL.Vec(QueueSkipSubmission)],
        ['query'],
      ),
    'getQueueSkipSubmissionsWithUsernames' : IDL.Func(
        [],
        [IDL.Vec(ExtendedQueueSkipSubmission)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUsername' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Text)], ['query']),
    'hasQueueBypass' : IDL.Func([], [IDL.Bool], ['query']),
    'hasUsername' : IDL.Func([], [IDL.Bool], ['query']),
    'isAdminUsername' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rejectCustomUsername' : IDL.Func([IDL.Principal], [], []),
    'removeAdminUsername' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitCustomUsername' : IDL.Func(
        [IDL.Text, PaymentMethod, IDL.Text],
        [],
        [],
      ),
    'submitQueueSkipPayment' : IDL.Func(
        [IDL.Text, GiftCardType, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateCartItemQuantity' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateCategory' : IDL.Func([IDL.Text, Category], [], []),
    'updatePaymentDetails' : IDL.Func([PaymentConfig], [], []),
    'updateProduct' : IDL.Func([IDL.Text, Product], [], []),
    'validateGeneratedUsername' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };