/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    username?: string;
    name: string;
    email: string;
    phoneNumber?: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Time = bigint;
export interface Category {
    name: string;
    description: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ExtendedQueueSkipSubmission {
    username?: string;
    submission: QueueSkipSubmission;
}
export interface QueueSkipSubmission {
    status: QueueSkipStatus;
    user: Principal;
    giftCardCode?: string;
    giftCardType: GiftCardType;
    timestamp: Time;
    transactionId: string;
}
export interface CustomUsernameSubmission {
    status: CustomUsernameStatus;
    paymentMethod: PaymentMethod;
    transactionDetails: string;
    user: Principal;
    requestedUsername: string;
    timestamp: Time;
}
export interface CartItem {
    productId: string;
    quantity: bigint;
}
export interface Product {
    id: string;
    imageUrls: Array<string>;
    name: string;
    description: string;
    productType: ProductType;
    image: ExternalBlob;
    priceGBP: number;
    quantityAvailable: bigint;
    gameCategory: string;
}
export interface PaymentConfig {
    queueSkipPriceGBP: number;
    instagramUrl: string;
    cryptoWalletAddress: string;
    ukGiftCardInstructions: string;
    usernameRegenerationPriceGBP: number;
    customUsernamePriceGBP: number;
    paypalEmail: string;
}
export enum CustomUsernameStatus {
    pendingReview = "pendingReview",
    approved = "approved",
    rejected = "rejected"
}
export enum GiftCardType {
    cryptocurrency = "cryptocurrency",
    tesco = "tesco",
    other = "other",
    starbucks = "starbucks",
    amazon = "amazon"
}
export enum PaymentMethod {
    crypto = "crypto",
    giftCard = "giftCard",
    paypal = "paypal"
}
export enum ProductType {
    clothes = "clothes",
    currency = "currency",
    account = "account"
}
export enum QueueSkipStatus {
    pendingReview = "pendingReview",
    flaggedFraudulent = "flaggedFraudulent",
    approved = "approved"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAdminPhoneNumber(phoneNumber: string): Promise<void>;
    addAdminUsername(username: string): Promise<void>;
    addToCart(productId: string, quantity: bigint): Promise<void>;
    approveCustomUsername(user: Principal): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearCart(): Promise<void>;
    createCategory(name: string, category: Category): Promise<void>;
    createProduct(id: string, product: Product): Promise<void>;
    createUsername(requestedUsername: string): Promise<void>;
    deleteCategory(name: string): Promise<void>;
    deleteProduct(id: string): Promise<void>;
    flagQueueSkipFraud(user: Principal): Promise<void>;
    getAllCategories(): Promise<Array<Category>>;
    getAllProducts(): Promise<Array<Product>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCart(): Promise<Array<CartItem>>;
    getCategory(name: string): Promise<Category>;
    getCustomUsernameSubmissions(): Promise<Array<CustomUsernameSubmission>>;
    getInstagramUrl(): Promise<string>;
    getPaymentDetails(): Promise<PaymentConfig>;
    getProduct(id: string): Promise<Product>;
    getQueueSkipSubmissions(): Promise<Array<QueueSkipSubmission>>;
    getQueueSkipSubmissionsWithUsernames(): Promise<Array<ExtendedQueueSkipSubmission>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUsername(_user: Principal): Promise<string | null>;
    hasPhoneNumber(): Promise<boolean>;
    hasQueueBypass(): Promise<boolean>;
    hasUsername(): Promise<boolean>;
    isAdminPhoneNumber(phoneNumber: string): Promise<boolean>;
    isAdminUsername(username: string): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    rejectCustomUsername(user: Principal): Promise<void>;
    removeAdminPhoneNumber(phoneNumber: string): Promise<void>;
    removeAdminUsername(username: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    savePhoneNumber(phoneNumber: string): Promise<void>;
    submitCustomUsername(requestedUsername: string, paymentMethod: PaymentMethod, transactionDetails: string): Promise<void>;
    submitQueueSkipPayment(transactionId: string, giftCardType: GiftCardType, giftCardCode: string | null): Promise<void>;
    updateCartItemQuantity(productId: string, quantity: bigint): Promise<void>;
    updateCategory(name: string, updatedCategory: Category): Promise<void>;
    updatePaymentDetails(config: PaymentConfig): Promise<void>;
    updateProduct(id: string, updatedProduct: Product): Promise<void>;
    validateGeneratedUsername(username: string): Promise<void>;
}
import type { CustomUsernameStatus as _CustomUsernameStatus, CustomUsernameSubmission as _CustomUsernameSubmission, ExtendedQueueSkipSubmission as _ExtendedQueueSkipSubmission, ExternalBlob as _ExternalBlob, GiftCardType as _GiftCardType, PaymentMethod as _PaymentMethod, Product as _Product, ProductType as _ProductType, QueueSkipStatus as _QueueSkipStatus, QueueSkipSubmission as _QueueSkipSubmission, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAdminPhoneNumber(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdminPhoneNumber(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdminPhoneNumber(arg0);
            return result;
        }
    }
    async addAdminUsername(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdminUsername(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdminUsername(arg0);
            return result;
        }
    }
    async addToCart(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToCart(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToCart(arg0, arg1);
            return result;
        }
    }
    async approveCustomUsername(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveCustomUsername(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveCustomUsername(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearCart(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCart();
            return result;
        }
    }
    async createCategory(arg0: string, arg1: Category): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCategory(arg0, arg1);
            return result;
        }
    }
    async createProduct(arg0: string, arg1: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(arg0, await to_candid_Product_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(arg0, await to_candid_Product_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createUsername(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createUsername(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUsername(arg0);
            return result;
        }
    }
    async deleteCategory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCategory(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async flagQueueSkipFraud(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.flagQueueSkipFraud(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.flagQueueSkipFraud(arg0);
            return result;
        }
    }
    async getAllCategories(): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCategories();
            return result;
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCart(): Promise<Array<CartItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCart();
            return result;
        }
    }
    async getCategory(arg0: string): Promise<Category> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategory(arg0);
            return result;
        }
    }
    async getCustomUsernameSubmissions(): Promise<Array<CustomUsernameSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomUsernameSubmissions();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomUsernameSubmissions();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInstagramUrl(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getInstagramUrl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInstagramUrl();
            return result;
        }
    }
    async getPaymentDetails(): Promise<PaymentConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentDetails();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentDetails();
            return result;
        }
    }
    async getProduct(arg0: string): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_Product_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_Product_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQueueSkipSubmissions(): Promise<Array<QueueSkipSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQueueSkipSubmissions();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQueueSkipSubmissions();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQueueSkipSubmissionsWithUsernames(): Promise<Array<ExtendedQueueSkipSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQueueSkipSubmissionsWithUsernames();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQueueSkipSubmissionsWithUsernames();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUsername(arg0: Principal): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsername(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsername(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasPhoneNumber(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasPhoneNumber();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasPhoneNumber();
            return result;
        }
    }
    async hasQueueBypass(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasQueueBypass();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasQueueBypass();
            return result;
        }
    }
    async hasUsername(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasUsername();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasUsername();
            return result;
        }
    }
    async isAdminPhoneNumber(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdminPhoneNumber(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdminPhoneNumber(arg0);
            return result;
        }
    }
    async isAdminUsername(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdminUsername(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdminUsername(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async rejectCustomUsername(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectCustomUsername(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectCustomUsername(arg0);
            return result;
        }
    }
    async removeAdminPhoneNumber(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAdminPhoneNumber(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAdminPhoneNumber(arg0);
            return result;
        }
    }
    async removeAdminUsername(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAdminUsername(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAdminUsername(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n44(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n44(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async savePhoneNumber(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePhoneNumber(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePhoneNumber(arg0);
            return result;
        }
    }
    async submitCustomUsername(arg0: string, arg1: PaymentMethod, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitCustomUsername(arg0, to_candid_PaymentMethod_n46(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitCustomUsername(arg0, to_candid_PaymentMethod_n46(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async submitQueueSkipPayment(arg0: string, arg1: GiftCardType, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitQueueSkipPayment(arg0, to_candid_GiftCardType_n48(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n50(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitQueueSkipPayment(arg0, to_candid_GiftCardType_n48(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n50(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateCartItemQuantity(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCartItemQuantity(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCartItemQuantity(arg0, arg1);
            return result;
        }
    }
    async updateCategory(arg0: string, arg1: Category): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCategory(arg0, arg1);
            return result;
        }
    }
    async updatePaymentDetails(arg0: PaymentConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePaymentDetails(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePaymentDetails(arg0);
            return result;
        }
    }
    async updateProduct(arg0: string, arg1: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, await to_candid_Product_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, await to_candid_Product_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async validateGeneratedUsername(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.validateGeneratedUsername(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateGeneratedUsername(arg0);
            return result;
        }
    }
}
function from_candid_CustomUsernameStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomUsernameStatus): CustomUsernameStatus {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_CustomUsernameSubmission_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomUsernameSubmission): CustomUsernameSubmission {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_ExtendedQueueSkipSubmission_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExtendedQueueSkipSubmission): ExtendedQueueSkipSubmission {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_GiftCardType_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GiftCardType): GiftCardType {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_ProductType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductType): ProductType {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
async function from_candid_Product_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Promise<Product> {
    return await from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_QueueSkipStatus_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QueueSkipStatus): QueueSkipStatus {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_QueueSkipSubmission_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QueueSkipSubmission): QueueSkipSubmission {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    imageUrls: Array<string>;
    name: string;
    description: string;
    productType: _ProductType;
    image: _ExternalBlob;
    priceGBP: number;
    quantityAvailable: bigint;
    gameCategory: string;
}): Promise<{
    id: string;
    imageUrls: Array<string>;
    name: string;
    description: string;
    productType: ProductType;
    image: ExternalBlob;
    priceGBP: number;
    quantityAvailable: bigint;
    gameCategory: string;
}> {
    return {
        id: value.id,
        imageUrls: value.imageUrls,
        name: value.name,
        description: value.description,
        productType: from_candid_ProductType_n18(_uploadFile, _downloadFile, value.productType),
        image: await from_candid_ExternalBlob_n20(_uploadFile, _downloadFile, value.image),
        priceGBP: value.priceGBP,
        quantityAvailable: value.quantityAvailable,
        gameCategory: value.gameCategory
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: [] | [string];
    name: string;
    email: string;
    phoneNumber: [] | [string];
}): {
    username?: string;
    name: string;
    email: string;
    phoneNumber?: string;
} {
    return {
        username: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.username)),
        name: value.name,
        email: value.email,
        phoneNumber: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.phoneNumber))
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _CustomUsernameStatus;
    paymentMethod: _PaymentMethod;
    transactionDetails: string;
    user: Principal;
    requestedUsername: string;
    timestamp: _Time;
}): {
    status: CustomUsernameStatus;
    paymentMethod: PaymentMethod;
    transactionDetails: string;
    user: Principal;
    requestedUsername: string;
    timestamp: Time;
} {
    return {
        status: from_candid_CustomUsernameStatus_n30(_uploadFile, _downloadFile, value.status),
        paymentMethod: from_candid_PaymentMethod_n32(_uploadFile, _downloadFile, value.paymentMethod),
        transactionDetails: value.transactionDetails,
        user: value.user,
        requestedUsername: value.requestedUsername,
        timestamp: value.timestamp
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _QueueSkipStatus;
    user: Principal;
    giftCardCode: [] | [string];
    giftCardType: _GiftCardType;
    timestamp: _Time;
    transactionId: string;
}): {
    status: QueueSkipStatus;
    user: Principal;
    giftCardCode?: string;
    giftCardType: GiftCardType;
    timestamp: Time;
    transactionId: string;
} {
    return {
        status: from_candid_QueueSkipStatus_n37(_uploadFile, _downloadFile, value.status),
        user: value.user,
        giftCardCode: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.giftCardCode)),
        giftCardType: from_candid_GiftCardType_n39(_uploadFile, _downloadFile, value.giftCardType),
        timestamp: value.timestamp,
        transactionId: value.transactionId
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: [] | [string];
    submission: _QueueSkipSubmission;
}): {
    username?: string;
    submission: QueueSkipSubmission;
} {
    return {
        username: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.username)),
        submission: from_candid_QueueSkipSubmission_n35(_uploadFile, _downloadFile, value.submission)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    clothes: null;
} | {
    currency: null;
} | {
    account: null;
}): ProductType {
    return "clothes" in value ? ProductType.clothes : "currency" in value ? ProductType.currency : "account" in value ? ProductType.account : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pendingReview: null;
} | {
    approved: null;
} | {
    rejected: null;
}): CustomUsernameStatus {
    return "pendingReview" in value ? CustomUsernameStatus.pendingReview : "approved" in value ? CustomUsernameStatus.approved : "rejected" in value ? CustomUsernameStatus.rejected : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    crypto: null;
} | {
    giftCard: null;
} | {
    paypal: null;
}): PaymentMethod {
    return "crypto" in value ? PaymentMethod.crypto : "giftCard" in value ? PaymentMethod.giftCard : "paypal" in value ? PaymentMethod.paypal : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pendingReview: null;
} | {
    flaggedFraudulent: null;
} | {
    approved: null;
}): QueueSkipStatus {
    return "pendingReview" in value ? QueueSkipStatus.pendingReview : "flaggedFraudulent" in value ? QueueSkipStatus.flaggedFraudulent : "approved" in value ? QueueSkipStatus.approved : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cryptocurrency: null;
} | {
    tesco: null;
} | {
    other: null;
} | {
    starbucks: null;
} | {
    amazon: null;
}): GiftCardType {
    return "cryptocurrency" in value ? GiftCardType.cryptocurrency : "tesco" in value ? GiftCardType.tesco : "other" in value ? GiftCardType.other : "starbucks" in value ? GiftCardType.starbucks : "amazon" in value ? GiftCardType.amazon : value;
}
async function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Promise<Array<Product>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Product_n16(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CustomUsernameSubmission>): Array<CustomUsernameSubmission> {
    return value.map((x)=>from_candid_CustomUsernameSubmission_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_QueueSkipSubmission>): Array<QueueSkipSubmission> {
    return value.map((x)=>from_candid_QueueSkipSubmission_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExtendedQueueSkipSubmission>): Array<ExtendedQueueSkipSubmission> {
    return value.map((x)=>from_candid_ExtendedQueueSkipSubmission_n42(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_GiftCardType_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GiftCardType): _GiftCardType {
    return to_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function to_candid_ProductType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductType): _ProductType {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
async function to_candid_Product_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Product): Promise<_Product> {
    return await to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n45(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    imageUrls: Array<string>;
    name: string;
    description: string;
    productType: ProductType;
    image: ExternalBlob;
    priceGBP: number;
    quantityAvailable: bigint;
    gameCategory: string;
}): Promise<{
    id: string;
    imageUrls: Array<string>;
    name: string;
    description: string;
    productType: _ProductType;
    image: _ExternalBlob;
    priceGBP: number;
    quantityAvailable: bigint;
    gameCategory: string;
}> {
    return {
        id: value.id,
        imageUrls: value.imageUrls,
        name: value.name,
        description: value.description,
        productType: to_candid_ProductType_n12(_uploadFile, _downloadFile, value.productType),
        image: await to_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value.image),
        priceGBP: value.priceGBP,
        quantityAvailable: value.quantityAvailable,
        gameCategory: value.gameCategory
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username?: string;
    name: string;
    email: string;
    phoneNumber?: string;
}): {
    username: [] | [string];
    name: string;
    email: string;
    phoneNumber: [] | [string];
} {
    return {
        username: value.username ? candid_some(value.username) : candid_none(),
        name: value.name,
        email: value.email,
        phoneNumber: value.phoneNumber ? candid_some(value.phoneNumber) : candid_none()
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductType): {
    clothes: null;
} | {
    currency: null;
} | {
    account: null;
} {
    return value == ProductType.clothes ? {
        clothes: null
    } : value == ProductType.currency ? {
        currency: null
    } : value == ProductType.account ? {
        account: null
    } : value;
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    crypto: null;
} | {
    giftCard: null;
} | {
    paypal: null;
} {
    return value == PaymentMethod.crypto ? {
        crypto: null
    } : value == PaymentMethod.giftCard ? {
        giftCard: null
    } : value == PaymentMethod.paypal ? {
        paypal: null
    } : value;
}
function to_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GiftCardType): {
    cryptocurrency: null;
} | {
    tesco: null;
} | {
    other: null;
} | {
    starbucks: null;
} | {
    amazon: null;
} {
    return value == GiftCardType.cryptocurrency ? {
        cryptocurrency: null
    } : value == GiftCardType.tesco ? {
        tesco: null
    } : value == GiftCardType.other ? {
        other: null
    } : value == GiftCardType.starbucks ? {
        starbucks: null
    } : value == GiftCardType.amazon ? {
        amazon: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
